apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: wallet-service
        image: codecorner/wallet-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        env:
        - name: SPRING_R2DBC_URL
          value: r2dbc:postgresql://postgres:5432/wallet_db
        - name: SPRING_R2DBC_USERNAME
          value: wallet_user
        - name: SPRING_R2DBC_PASSWORD
          value: wallet_pass
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: wallet-service
  ports:
  - port: 8002